var MainCtrl, QNAS, app;

QNAS = [
  {
    name: 'TS-1079 Pro',
    photo: 'http://www.qnap.com/i/_images/product/items/18_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=18',
    vmware: true,
    cpu: 'Dual Core Intel® Core™ i3-2120 Processor 3.3 GHz',
    cpu_core: 'Intel',
    ram: '2 GB DDR3',
    ram_size: 2000,
    hdd: '10 x 3.5" SATA 6Gb/s, SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 10,
    hdd_sata3: true,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠 (可額外安裝dual-port 10Gb和1Gb網路卡模組)',
    lan_num: 2,
    lan_10g: true,
    usb: '2 個 USB 3.0（正面：1；背面：1）, 4 個 USB 2.0（背面：4）,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 6,
    usb_3: true,
    eSATA: 2,
    qts4: false,
    app: []
  }, {
    name: 'TS-879 Pro',
    photo: 'http://www.qnap.com/i/_images/product/items/15_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=15',
    vmware: true,
    cpu: 'Dual Core Intel® Core™ i3-2120 Processor 3.3 GHz',
    cpu_core: 'Intel',
    ram: '2 GB DDR3',
    ram_size: 2000,
    hdd: '8 x 3.5" SATA 6Gb/s, SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 8,
    hdd_sata3: true,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠 (可額外安裝dual-port 10Gb和1Gb網路卡模組)',
    lan_num: 2,
    lan_10g: true,
    usb: '2 個 USB 3.0（正面：1；背面：1）, 4 個 USB 2.0（背面：4）,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 6,
    usb_3: true,
    eSATA: 2,
    qts4: false,
    app: []
  }, {
    name: 'TS-869 Pro',
    photo: 'http://www.qnap.com/i/_images/product/items/24_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=24',
    vmware: true,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '8 x 3.5" SATA 6Gb/s, SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 8,
    hdd_sata3: true,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 5 個 USB 2.0（正面：1；背面：4）,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 7,
    usb_3: true,
    eSATA: 2,
    qts4: false,
    app: []
  }, {
    name: 'TS-669 Pro',
    photo: 'http://www.qnap.com/i/_images/product/items/23_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=23',
    vmware: true,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '6 x 3.5" SATA 6Gb/s, SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 6,
    hdd_sata3: true,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 5 個 USB 2.0（正面：1；背面：4）,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 7,
    usb_3: true,
    eSATA: 2,
    qts4: false,
    app: []
  }, {
    name: 'TS-569 Pro',
    photo: 'http://www.qnap.com/i/_images/product/items/22_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=22',
    vmware: true,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '5 x 3.5" SATA 6Gb/s, SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 5,
    hdd_sata3: true,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 5 個 USB 2.0（正面：1；背面：4）,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 7,
    usb_3: true,
    eSATA: 2,
    qts4: false,
    app: []
  }, {
    name: 'TS-469 Pro',
    photo: 'http://www.qnap.com/i/_images/product/items/21_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=21',
    vmware: true,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '4 x 3.5" SATA 6Gb/s, SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 4,
    hdd_sata3: true,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 5 個 USB 2.0（正面：1；背面：4）,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 7,
    usb_3: true,
    eSATA: 2,
    qts4: false,
    app: []
  }, {
    name: 'TS-269 Pro',
    photo: 'http://www.qnap.com/i/_images/product/items/28_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=28',
    vmware: true,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '2 x 3.5" SATA 6Gb/s, SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 2,
    hdd_sata3: true,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 3 個 USB 2.0（正面：1；背面：3） ,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 5,
    usb_3: true,
    eSATA: 1,
    qts4: false,
    app: []
  }, {
    name: 'TS-869L',
    photo: 'http://www.qnap.com/i/_images/product/items/35_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=35',
    vmware: false,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '8 x 3.5" SATA 3Gb/s硬碟或 2.5" SATA, SSD',
    hdd_bay: 8,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 5 個 USB 2.0（正面：1；背面：4） ,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 7,
    usb_3: true,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-669L',
    photo: 'http://www.qnap.com/i/_images/product/items/34_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=34',
    vmware: false,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '6 x 3.5" SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 6,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 5 個 USB 2.0（正面：1；背面：4） ,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 7,
    usb_3: true,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-569L',
    photo: 'http://www.qnap.com/i/_images/product/items/33_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=33',
    vmware: false,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '5 x 3.5" SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 5,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 5 個 USB 2.0（正面：1；背面：4） ,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 7,
    usb_3: true,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-469L',
    photo: 'http://www.qnap.com/i/_images/product/items/32_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=32',
    vmware: false,
    cpu: 'Intel® Atom™ 2.13GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '4 x 3.5" SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 4,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 5 個 USB 2.0（正面：1；背面：4） ,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 7,
    usb_3: true,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-269L',
    photo: 'http://www.qnap.com/i/_images/product/items/31_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=31',
    vmware: false,
    cpu: 'Intel® Atom™ 1.86 GHz Dual-core Processor',
    cpu_core: 'Intel',
    ram: '1GB RAM',
    ram_size: 1000,
    hdd: '2 x 3.5" SATA 3Gb/s 硬碟或 2.5" SATA, SSD',
    hdd_bay: 2,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '2 個 USB 3.0（背面）, 3 個 USB 2.0（正面：1；背面：3）,支援 USB 印表機、隨身碟、USB hub 及 USB UPS 等',
    usb_num: 5,
    usb_3: true,
    eSATA: 1,
    qts4: true,
    app: []
  }, {
    name: 'TS-412',
    photo: 'http://www.qnap.com/i/_images/product/items/12_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=12',
    vmware: false,
    cpu: 'Marvell 6281 1.2GHz',
    cpu_core: 'Marvell',
    ram: '256MB DDRII',
    ram_size: 256,
    hdd: '4 x 3.5" 或 2.5" SATA I/II 硬碟',
    hdd_bay: 4,
    hdd_sata3: false,
    hdd_ssd: false,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 網路埠',
    lan_num: 2,
    lan_10g: false,
    usb: '4 個 USB 2.0（正面：1；背面：3）',
    usb_num: 4,
    usb_3: false,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-212',
    photo: 'http://www.qnap.com/i/_images/product/items/10_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=10',
    vmware: false,
    cpu: 'Marvell 6281 1.2GHz',
    cpu_core: 'Marvell',
    ram: '256MB DDRII',
    ram_size: 256,
    hdd: '2 x 3.5" SATA I/II 硬碟',
    hdd_bay: 2,
    hdd_sata3: false,
    hdd_ssd: false,
    hdd_35: true,
    hdd_25: false,
    lan: '1 x Gigabit RJ-45 網路埠',
    lan_num: 1,
    lan_10g: false,
    usb: '3 個 USB 2.0 (正面：1；背面：2)',
    usb_num: 3,
    usb_3: false,
    eSATA: 0,
    qts4: true,
    app: []
  }, {
    name: 'TS-112',
    photo: 'http://www.qnap.com/i/_images/product/items/7_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=7',
    vmware: false,
    cpu: 'Marvell 6281 1.2GHz',
    cpu_core: 'Marvell',
    ram: '256MB DDRII',
    ram_size: 256,
    hdd: '1 x 3.5" SATA I/II 硬碟',
    hdd_bay: 1,
    hdd_sata3: false,
    hdd_ssd: false,
    hdd_35: true,
    hdd_25: false,
    lan: '1 x Gigabit RJ-45 網路埠',
    lan_num: 1,
    lan_10g: false,
    usb: '3 個 USB 2.0 (正面：1；背面：2)',
    usb_num: 3,
    usb_3: false,
    eSATA: 0,
    qts4: true,
    app: []
  }, {
    name: 'TS-421',
    photo: 'http://www.qnap.com/i/_images/product/items/99_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=99',
    vmware: false,
    cpu: 'Marvell 2.0GHz',
    cpu_core: 'Marvell',
    ram: '1GB DDR3',
    ram_size: 1000,
    hdd: '4 x 3.5" SATA or 2.5” SATA II/SSD HDD',
    hdd_bay: 4,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 Ethernet port',
    lan_num: 2,
    lan_10g: false,
    usb: '2 x USB 3.0 port (Back), 2 x USB 2.0 port (Front x1; Back x1)',
    usb_num: 4,
    usb_3: true,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-221',
    photo: 'http://www.qnap.com/i/_images/product/items/96_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=96',
    vmware: false,
    cpu: 'Marvell 2.0GHz',
    cpu_core: 'Marvell',
    ram: '1GB DDR3',
    ram_size: 1000,
    hdd: '2 x 3.5" SATA or 2.5” SATA II/SSD HDD',
    hdd_bay: 2,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '1 x Gigabit RJ-45 Ethernet port',
    lan_num: 1,
    lan_10g: false,
    usb: '2 x USB 3.0 port (Back), 1 x USB 2.0 port (Front)',
    usb_num: 3,
    usb_3: true,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-121',
    photo: 'http://www.qnap.com/i/_images/product/items/103_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=103',
    vmware: false,
    cpu: 'Marvell 2.0GHz',
    cpu_core: 'Marvell',
    ram: '1GB DDR3',
    ram_size: 1000,
    hdd: '1 x 3.5" SATA or 2.5” SATA II/SSD HDD',
    hdd_bay: 1,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '1 x Gigabit RJ-45 Ethernet port',
    lan_num: 1,
    lan_10g: false,
    usb: '2 x USB 3.0 port (Back), 1 x USB 2.0 port (Front)',
    usb_num: 3,
    usb_3: true,
    eSATA: 1,
    qts4: true,
    app: []
  }, {
    name: 'TS-420',
    photo: 'http://www.qnap.com/i/_images/product/items/100_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=100',
    vmware: false,
    cpu: 'Marvell 1.6GHz',
    cpu_core: 'Marvell',
    ram: '512MB DDR3',
    ram_size: 512,
    hdd: '4 x 3.5" SATA or 2.5” SATA II/SSD HDD',
    hdd_bay: 4,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '2 x Gigabit RJ-45 Ethernet port',
    lan_num: 2,
    lan_10g: false,
    usb: '2 x USB 3.0 port (Back), 2 x USB 2.0 port  (Front x1; Back x1)',
    usb_num: 4,
    usb_3: true,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-220',
    photo: 'http://www.qnap.com/i/_images/product/items/101_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=101',
    vmware: false,
    cpu: 'Marvell 1.6GHz',
    cpu_core: 'Marvell',
    ram: '512MB DDR3',
    ram_size: 512,
    hdd: '2 x 3.5" SATA or 2.5” SATA II/SSD HDD',
    hdd_bay: 2,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '1 x Gigabit RJ-45 Ethernet port',
    lan_num: 1,
    lan_10g: false,
    usb: '2 x USB 3.0 port (Back), 1 x USB 2.0 port (Front)',
    usb_num: 3,
    usb_3: true,
    eSATA: 2,
    qts4: true,
    app: []
  }, {
    name: 'TS-120',
    photo: 'http://www.qnap.com/i/_images/product/items/102_s.png',
    page: 'http://www.qnap.com/i/cht/product/model.php?II=102',
    vmware: false,
    cpu: 'Marvell 1.6GHz',
    cpu_core: 'Marvell',
    ram: '512MB DDR3',
    ram_size: 512,
    hdd: '1 x 3.5" SATA or 2.5” SATA II/SSD HDD',
    hdd_bay: 1,
    hdd_sata3: false,
    hdd_ssd: true,
    hdd_35: true,
    hdd_25: true,
    lan: '1 x Gigabit RJ-45 Ethernet port',
    lan_num: 1,
    lan_10g: false,
    usb: '2 x USB 3.0 port (Back), 1 x USB 2.0 port (Front)',
    usb_num: 3,
    usb_3: true,
    eSATA: 1,
    qts4: true,
    app: []
  }
];

app = angular.module('app', ['ui.bootstrap']);

app.filter('filter', function() {
  return function(items, factor) {
    var response;

    console.log(factor);
    response = [];
    angular.forEach(items, function(item, key) {
      if (factor.cpu_core !== 'Any' && factor.cpu_core !== item.cpu_core) {
        return;
      }
      if (factor.qts4 && item.qts4 === false) {
        return;
      }
      if (factor.vmware && item.vmware === false) {
        return;
      }
      if (!factor.hdd_bay[item.hdd_bay]) {
        return;
      }
      if (factor.hdd_sata3 && item.hdd_sata3 === false) {
        return;
      }
      if (factor.hdd_ssd && item.hdd_ssd === false) {
        return;
      }
      if (factor.eSATA > item.eSATA) {
        return;
      }
      if (factor.lan_num > item.lan_num) {
        return;
      }
      if (factor.lan_10g && item.lan_10g === false) {
        return;
      }
      if (factor.usb_num > item.usb_num) {
        return;
      }
      if (factor.usb_3 && item.usb_3 === false) {
        return;
      }
      return this.push(item);
    }, response);
    return response;
  };
});

MainCtrl = function($scope) {
  $scope.items = QNAS;
  $scope.factor = {
    cpu_core: 'Any',
    qts4: false,
    vmware: false,
    hdd_bay: {
      1: true,
      2: true,
      4: true,
      5: true,
      6: true,
      8: true,
      10: true
    },
    hdd_sata3: false,
    hdd_ssd: false,
    eSATA: 0,
    lan_num: 0,
    lan_10g: false,
    usb_num: 0,
    usb_3: false
  };
  $scope.product = {};
  angular.forEach($scope.items, function(item, key) {
    return $scope.product[item.name] = item;
  });
  $scope.buy = function(name) {
    return window.open('http://ecshweb.pchome.com.tw/search/v2/?q=' + $scope.product[name].name);
  };
  return $scope.page = function(name) {
    return window.open($scope.product[name].page);
  };
};
